import 'dart:io';
import 'package:protoc_plugin/src/gen/google/protobuf/compiler/plugin.pb.dart';
import 'parser/descriptor_parser.dart';
import 'model/service_model.dart';
import 'format_formatter.dart';

class CodeGenerator {
  final DescriptorParser _parser = DescriptorParser();

  CodeGeneratorResponse generate(CodeGeneratorRequest request) {
    try {
      final services = _parser.parse(request.protoFile);
      final files = <CodeGeneratorResponse_File>[];

      for (final service in services) {
        files.add(CodeGeneratorResponse_File(
          name: '${service.name.toLowerCase()}_service.dart',
          content: _generateServiceFacade(service),
        ));
      }

      return CodeGeneratorResponse(file: files);
    } catch (e, st) {
      return CodeGeneratorResponse(
        error: 'Generation failed: $e\n$st',
      );
    }
  }

  String _generateServiceFacade(ServiceModel service) {
    final raw = [
      '// Generated by protoc-gen-dart-unified. DO NOT EDIT.',
      '// Source: ${service.name}',
      '',
      'class ${service.name}Client {',
      '  // TODO: implement facade generation',
      '}',
    ].join('\n');
    return formatDartSource(raw);
  }
}

Future<void> runCodeGenerator() async {
  final bytes = <int>[];
  await for (final chunk in stdin) {
    bytes.addAll(chunk);
  }
  final request = CodeGeneratorRequest.fromBuffer(bytes);
  final generator = CodeGenerator();
  final response = generator.generate(request);
  stdout.add(response.writeToBuffer());
}
