import 'package:dio/dio.dart';
import 'transport.dart';
import 'api_exception.dart';

/// Creates a transport for native platforms (iOS, Android, Desktop).
///
/// Returns an HttpTransport for HTTP-only mode, or null if gRPC is needed
/// but no gRPC client is available.
Transport? createTransport(String endpoint) {
  return HttpTransport(endpoint);
}

/// HTTP transport implementation using dio.
class HttpTransport implements Transport {
  final Dio _dio;

  HttpTransport(String endpoint) : _dio = Dio(BaseOptions(baseUrl: endpoint));

  @override
  Future<T> unaryCall<T>(
    String serviceName,
    String methodName,
    Object request, {
    RpcCallOptions? options,
  }) async {
    // Phase 1 scaffold: the actual HTTP path/query/body mapping
    // is generated by the code generator. This transport provides
    // the runtime execution layer.
    try {
      final response = await _dio.request<dynamic>(
        '/$serviceName/$methodName',
        data: request,
        options: Options(
          method: 'POST',
          headers: options?.headers,
          sendTimeout: options?.timeout,
          receiveTimeout: options?.timeout,
        ),
      );
      // Response deserialization is handled by the generated code
      return response.data as T;
    } on DioException catch (e) {
      throw _mapDioException(e);
    }
  }

  @override
  Stream<T> serverStream<T>(
    String serviceName,
    String methodName,
    Object request, {
    RpcCallOptions? options,
  }) {
    // SSE streaming deferred to Phase 3
    throw UnimplementedError(
        'HTTP server streaming requires SSE, deferred to Phase 3');
  }

  ApiException _mapDioException(DioException e) {
    final status = e.response?.statusCode ?? 0;
    // Map HTTP status to gRPC code, then to ApiException
    final grpcCode = _httpStatusToGrpcCode(status);
    final message = e.message ?? 'HTTP error';
    return _createApiException(grpcCode, message);
  }

  int _httpStatusToGrpcCode(int status) {
    // Reverse mapping: HTTP status → gRPC canonical code
    return switch (status) {
      400 => 3,  // INVALID_ARGUMENT
      401 => 16, // UNAUTHENTICATED
      403 => 7,  // PERMISSION_DENIED
      404 => 5,  // NOT_FOUND
      409 => 6,  // ALREADY_EXISTS
      429 => 8,  // RESOURCE_EXHAUSTED
      422 => 3,  // INVALID_ARGUMENT (unprocessable entity)
      500 => 13, // INTERNAL
      501 => 12, // UNIMPLEMENTED
      502 => 14, // UNAVAILABLE
      503 => 14, // UNAVAILABLE
      504 => 4,  // DEADLINE_EXCEEDED
      _ => 2,    // UNKNOWN
    };
  }

  ApiException _createApiException(int code, String message) {
    return switch (code) {
      1 => CancelledException(message),
      2 => UnknownException(message),
      3 => InvalidArgumentException(message),
      4 => RpcTimeoutException(message),
      5 => NotFoundException(message),
      6 => AlreadyExistsException(message),
      7 => PermissionDeniedException(message),
      8 => ResourceExhaustedException(message),
      9 => FailedPreconditionException(message),
      10 => AbortedException(message),
      11 => OutOfRangeException(message),
      12 => UnimplementedException(message),
      13 => InternalServerException(message),
      14 => UnavailableException(message),
      15 => DataLossException(message),
      16 => UnauthenticatedException(message),
      _ => InternalServerException(message),
    };
  }
}

/// gRPC transport implementation that delegates to generated *ServiceClient.
///
/// This is a scaffold — full implementation requires the generated
/// *ServiceClient classes from protoc-gen-dart.
class GrpcTransport implements Transport {
  final Map<String, dynamic> _clients;

  GrpcTransport(this._clients);

  @override
  Future<T> unaryCall<T>(
    String serviceName,
    String methodName,
    Object request, {
    RpcCallOptions? options,
  }) {
    // Phase 1 scaffold: gRPC delegation requires generated *ServiceClient
    throw UnimplementedError(
        'gRPC transport requires generated *ServiceClient for $serviceName');
  }

  @override
  Stream<T> serverStream<T>(
    String serviceName,
    String methodName,
    Object request, {
    RpcCallOptions? options,
  }) {
    // Phase 1 scaffold: gRPC server streaming requires generated *ServiceClient
    throw UnimplementedError(
        'gRPC server streaming requires generated *ServiceClient for $serviceName');
  }
}
